# Generated by Django 3.2.7 on 2021-11-30 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cropModel',
            fields=[
                ('primaryKey', models.BigAutoField(db_column='pk', primary_key=True, serialize=False, verbose_name='pk')),
                ('name', models.CharField(blank=True, default='작물', max_length=30)),
                ('info', models.TextField(blank=True, default='')),
                ('image', models.ImageField(default='v2/default_Crop.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='currCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='v2.cropmodel')),
            ],
        ),
    ]
